apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::582282256496:role/eks-node-group
      username: system:node:{{EC2PrivateDNSName}}
      groups:
      - system:bootstrappers
      - system:nodes
    - rolearn: arn:aws:iam::582282256496:role/mh-devops
      username: devops
      groups:
        - system:masters
    - rolearn: arn:aws:iam::582282256496:role/mh-developer
      username: developer
      groups:
        - aws:iam-mh-developer-role
